image: orellabac/workspace-full

tasks:
  - command: git secrets --install


vscode:
  extensions:
  - gitlab.gitlab-workflow
  - orellabaccr.snowqm-extension
  - orellabaccr.snowconvert-extension-pack
  - https://snowstudiobackups.blob.core.windows.net/extensions/CodeStream.codestream-10.6.1.vsix
