
image: orellabac/snowstudio-testrunner2

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging

stages:
  - test-scripts

## You can use an structure like this
test-folder1:
  stage: test-scripts
  script:
    - export FOLDER_NAME=folder1
    - echo "ProjectDir $CI_PROJECT_DIR"
    - export GITPOD_REPO_ROOT=$CI_PROJECT_DIR
    - export PYTHONPATH=$CI_PROJECT_DIR/Target/script
    - dotenv run pytest "tests/test_$FOLDER_NAME.py"  --capture=tee-sys --junitxml=results-$FOLDER_NAME.xml
    - sh /collect_coverage.sh
    - coverage xml
    - cp coverage.xml coverage-$FOLDERNAME.xml
    - coverage report
  artifacts:
    when: always
    reports:
      junit: results-*.xml
      cobertura: coverage-*.xml   